# https://github.com/AlexisLessard/docker-prometheus/blob/master/tasks/install_grafana.yml
- name: Ensure grafana's directory exists
  file:
        path: /srv/grafana/ 
        mode: 0755
        state: directory 

- name: Ensure grafana's storage directory existe
  file:
        path: "{{ grafana_volume_storage_source }}" 
        state: directory 

- name: Copy datasource file to grafana
  template:
    src: datasources.yml.j2
    dest: "{{ grafana_volume_datasource_source }}"  
    owner: root
    mode: 0644

- name: Start Grafana container
  docker_container:
    name: "{{ grafana_container_name }}"
    hostname: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}" 
    published_ports:
      - 3000:3000 
    volumes: "{{ grafana_volume_mountinstructions }}"
    links:
      - "{{ prometheus_container_name }}"
    env: "{{ grafana_environment_variables }}" 
    restart_policy: always
