---
-
  hosts: localhost
  become: true
  name: Database with monitoring
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  dependencies:
    - nginxinc.nginx

  roles:
    - role: docker
    - role: postgres
    - role: postgres_exporter
    - role: prometheus
    - role: grafana
    - role: nginxinc.nginx