---
-
  hosts: localhost
  become: true
  name: Database with monitoring
  vars: 
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: docker
    - role: postgres
    - role: postgres_exporter
    - role: prometheus
    - role: grafana
    - role: geerlingguy.nginx

# find way how to get it into galaxy nginx
# nginx_vhosts:
# - 
#  extra_parameters: |
#    location /prometheus {
#      proxy_pass http://prometheus:9090/;
#    }
#    location /grafana {
#      proxy_pass http://grafana:3000/;
#    }