# https://github.com/wrouesnel/postgres_exporter

- name: Start exporter contaner
  docker_container:
    image: wrouesnel/postgres_exporter
    name: exporter
    env:
      DATA_SOURCE_NAME: "postgresql://roihunter:roihunter@postgresql:5432/postgres"
