# https://github.com/AlexisLessard/docker-prometheus/blob/master/tasks/install_prometheus.yml

#- name: Ensure prometheus data directory owner is nobody
#  file:
#        path: "{{ prometheus_volume_source}}"
#        owner: nobody
#        group: nobody
#        mode: 0777 
#        state: directory 

- name: Copy config file
  template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_volume_source}}/prometheus.yml"
        owner: root
        mode: 0666 

# Use rules only if needed download rule file from original repo to make it work
#- name: Copy rule file
#  copy:
#    src: "{{ prometheus_rule_file_name }}"
#    dest: "{{ prometheus_volume_source }}/{{ prometheus_rule_file_name }}"
#    owner: root
#    mode: 0666

- name: Start prometheus container
  docker_container:
    name: "{{ prometheus_container_name }}"
    hostname: "{{ prometheus_container_name }}"
    image: "{{ prometheus_image }}"
    command: "{% for key in prometheus_commandline_args %}--{{key}}={{prometheus_commandline_args[key]}} {% endfor %}"
    published_ports:
      - 9090:9090
    volumes:
      - "{{ prometheus_volume_mountinstruction }}" 
    restart_policy: always