# partly based on https://github.com/Yoctol/ansible-docker-postgres/blob/master/tasks/main.yml
---

- name: Deploy PG DB
  docker_container:
    name: postgres
    image: postgres:11.5-alpine
    state: started
    restart_policy: always
    env:
      POSTGRES_PASSWORD: {{ master_pwd }}
      POSTGRES_USER: {{ master_name }}
      POSTGRES_DB: {{ master_db }}
    volumes:
      - /var/lib/docker/volumes/postgres-data/_data
    published_ports:
      - 127.0.0.1:5432:5432

# solve problem wit not accesible DB https://stackoverflow.com/questions/50784320/postgresql-port-not-ready-for-an-ansible-task
- name: hold until Postgresql is up and running 
  wait_for:
    port: 5432

- name: Create DB
  postgresql_db:
    conn_limit: 100 # limit connections to not overload server
    name: {{ rwdb }}
    state: present
    login_host: localhost
    login_user: {{ master_name }}
    login_password: {{ master_pwd }}

# Create user https://docs.ansible.com/ansible/latest/modules/postgresql_user_module.html
- name: Create user
  postgresql_user:
    db: {{ rwdb }}
    name: rwuser
    password: roihunter
    login_host: localhost
    login_user: {{ master_name }}
    login_password: {{ master_pwd }}


#TODO add some tests (but how?), create user, 