# partly based on https://github.com/Yoctol/ansible-docker-postgres/blob/master/tasks/main.yml
---

- name: Deploy PG DB
  docker_container:
    name: postgres
    image: postgres:11.5-alpine
    state: started
    restart_policy: always
    env:
      POSTGRES_PASSWORD: roihunter
      POSTGRES_USER: roihunter
      POSTGRES_DB: roihunter
    volumes:
      - /var/lib/docker/volumes/postgres-data/_data
    published_ports:
      - 127.0.0.1:5432:5432

# Create user https://docs.ansible.com/ansible/latest/modules/postgresql_user_module.html
- name: Create user
  postgresql_user:
    name: rwuser
    password: roihunter


#TODO add some tests (but how?), create user, 